version: "3.8"
services:
  coindashboard-backend:
    build: .
    restart: always
    ports:
      - 8080:8080
  mongo:
    build: ./mongoDB
    container_name: mongoDB
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
volumes:
  mongodbdata:

