name: build

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Inject secrets to a file
        run: echo $'secret.key=${{ secrets.APP_KEY }}\nsecret.iv=${{ secrets.APP_IV }}' >> ./src/main/resources/secrets.properties && cp ./src/main/resources/secrets.properties ./src/test/resources/secrets.properties
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          architecture: 'x64'
          cache: maven

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run the Maven verify phase
        run: >
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar 
          -Dsonar.organization=cuttingedgecommunity 
          -Dsonar.projectKey=CuttingEdgeCommunity_coindashboard-backend 
          -Dsonar.host.url=https://sonarcloud.io

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/cuttingedgecommunity/coindashboard-backend:latest
          secrets: |
            "app.key=${{ secrets.APP_KEY }}"
            "app.iv={{ secrets.APP_IV }}"
