name: traefik-workflow


env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


# Controls when the workflow will run
on:

  push:
    paths:
      - traefik/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  
  deploy-traefik:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          context: ./mongoDB
          push: true
          tags: ghcr.io/cuttingedgecommunity/coindashboard-traefik:latest